CREATE DATABASE nile;
USE nile;

-- 用户表
CREATE TABLE user(
`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
`name` VARCHAR(50) NOT NULL COMMENT '用户名',
`phone` CHAR(11) NOT NULL COMMENT '手机号',
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY (`id`),
KEY `idx_user_phone`(`user_phone`)
)ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8 COMMENT='用户表';

-- 图书表
CREATE TABLE book(
`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '图书ID',
`name` VARCHAR(50) NOT NULL COMMENT '书名',
`author` VARCHAR(50) COMMENT '作者',
`publishing_company` VARCHAR(50) NOT NULL COMMENT '出版社',
`price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '价格',
)ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8 COMMENT='图书表';





